# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-21 20:58
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pathway', '0008_auto_20170711_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathway',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=254, populate_from='populate_slug', unique=True),
        ),
        migrations.AlterField(
            model_name='pathwayelement',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=254, populate_from='name', unique=True),
        ),
    ]
