# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-21 20:58
from __future__ import unicode_literals

import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('badgeuser', '0024_auto_20200106_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badgeuser',
            name='badgrapp',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainsite.BadgrApp'),
        ),
        migrations.AlterField(
            model_name='badgeuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
