# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-21 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0022_badgrapp_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationinfo',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
