# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-21 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backpack', '0012_auto_20200106_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backpackbadgeshare',
            name='provider',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter'), ('pinterest', 'Pinterest')], max_length=254),
        ),
        migrations.AlterField(
            model_name='backpackcollectionshare',
            name='provider',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter'), ('pinterest', 'Pinterest')], max_length=254),
        ),
    ]
